### ISSUE TITLE
Error al cargar un nuevo TileSet

### ISSUE THREAD

**Issue by Derillo** [ao-libre/finisterra#176]
```
Exception in thread "main" java.lang.RuntimeException: Actor: List
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:202)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:152)
	at com.badlogic.gdx.scenes.scene2d.utils.Selection.fireChangeEvent(Selection.java:224)
	at com.badlogic.gdx.scenes.scene2d.utils.Selection.set(Selection.java:109)
	at com.badlogic.gdx.scenes.scene2d.utils.ArraySelection.validate(ArraySelection.java:81)
	at com.badlogic.gdx.scenes.scene2d.ui.List.setItems(List.java:365)
	at design.screens.views.View.loadItems(View.java:301)
	at design.screens.views.View$3.clicked(View.java:198)


public void loadItems(Optional<T> selection) {
        Array<T> items = new Array<>();
        designer.get().values().forEach(items::add);
        sort(items);
        list.setItems(items)
```;

**Comment by Derillo** [comment]
Con algunas imagenes da error y con otras no.
Con las que no da error al modificar las Filas y columnas devuelve el siguiente error:
```
Exception in thread "main" com.google.common.cache.CacheLoader$InvalidCacheLoadException: CacheLoader returned null for key 0.
	at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2315)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2279)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3953)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3976)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4960)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4966)
	at game.handlers.AnimationHandler.getTexture(AnimationHandler.java:149)
	at graphics.AOImageActor.<init>(AOImageActor.java:45)
	at design.screens.views.TileSetView$TileSetPreview.show(TileSetView.java:97)
	at design.screens.views.TileSetView$TileSetPreview.show(TileSetView.java:73)
	at design.screens.views.View.refreshPreview(View.java:136)
	at design.screens.views.View.onModify(View.java:252)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at design.editors.fields.FieldEditor.onModify(FieldEditor.java:91)
	at design.editors.fields.IntegerEditor$2$1.lambda$run$0(IntegerEditor.java:113)
```

**Comment by Derillo** [comment]
Solucionado en #294
