### ISSUE TITLE
Error al leer el Mapa(no encuentra un mapa aledaño)

### ISSUE THREAD

**Issue by Derillo** [ao-libre/finisterra#67]
Dungeon Dragon 
Pos 166 - 29 - 33
Problem: Crash Cliente , Server: No problem idetify

**Errores:**
03:42  INFO: Failed to read map -1
Exception in thread "LWJGL Application" java.lang.NullPointerException
        at game.systems.render.world.MapGroundRenderingSystem.drawGraphicInLayer(MapGroundRenderingSystem.java:55)
        at game.systems.render.world.MapGroundRenderingSystem.lambda$drawRange$0(MapGroundRenderingSystem.java:49)
        at game.systems.render.world.WorldRenderingSystem$UserRange.forEachTile(WorldRenderingSystem.java:158)
        at game.systems.render.world.MapGroundRenderingSystem.drawRange(MapGroundRenderingSystem.java:43)
        at game.systems.render.world.MapGroundRenderingSystem.renderWorld(MapGroundRenderingSystem.java:39)
        at game.systems.render.world.MapGroundRenderingSystem.processSystem(MapGroundRenderingSystem.java:64)
        at com.artemis.BaseSystem.process(BaseSystem.java:46)
        at com.artemis.InvocationStrategy.process(InvocationStrategy.java:25)
        at com.artemis.World.process(World.java:385)
        at game.screens.GameScreen.update(GameScreen.java:153)
        at game.screens.GameScreen.render(GameScreen.java:180)
        at com.badlogic.gdx.Game.render(Game.java:46)
        at game.AOGame.render(AOGame.java:45)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

**Comment by Derillo** [comment]
Vuelve a suceder en Otro mapa en la misma coordenada de X: 40 - 29 - 78 (catacumbas ulla)

09:16  INFO: Failed to read map -1
Exception in thread "LWJGL Application" java.lang.NullPointerException
        at game.systems.render.world.MapGroundRenderingSystem.drawGraphicInLayer(MapGroundRenderingSystem.java:55)
        at game.systems.render.world.MapGroundRenderingSystem.lambda$drawRange$0(MapGroundRenderingSystem.java:49)
        at game.systems.render.world.WorldRenderingSystem$UserRange.forEachTile(WorldRenderingSystem.java:158)
        at game.systems.render.world.MapGroundRenderingSystem.drawRange(MapGroundRenderingSystem.java:43)
        at game.systems.render.world.MapGroundRenderingSystem.renderWorld(MapGroundRenderingSystem.java:39)
        at game.systems.render.world.MapGroundRenderingSystem.processSystem(MapGroundRenderingSystem.java:64)
        at com.artemis.BaseSystem.process(BaseSystem.java:46)
        at com.artemis.InvocationStrategy.process(InvocationStrategy.java:25)
        at com.artemis.World.process(World.java:385)
        at game.screens.GameScreen.update(GameScreen.java:153)
        at game.screens.GameScreen.render(GameScreen.java:180)
        at com.badlogic.gdx.Game.render(Game.java:46)
        at game.AOGame.render(AOGame.java:45)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

**Comment by guidota** [comment]
Para arreglar esto hay que ir al mapa (mapX.json) y modificar los neighbors. El orden es el siguiente:
neighbors[left, up, right, down]. Para indicar que no hay mapa se usa el -1

**Comment by Derillo** [comment]
Solucionado con la implementación de mundo continuo 2019
